CREATE TABLE image (
    id UUID NOT NULL PRIMARY KEY,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    index INTEGER NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);