CREATE TABLE slider (
    id UUID NOT NULL PRIMARY KEY,
    colour TEXT,
    title TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
)