server:
  port: 8080
management:
  server:
    port: 8081
  endpoint:
    info:
      enabled: false
    health:
      show-details: always

spring:
  main:
    banner-mode: off
  profiles:
    active: "dev"
  swagger:
    endpoint: /swagger-ui.html
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    database: postgresql
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    driver-class-name: org.postgresql.Driver

---

spring:
  profiles: dev
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  datasource:
    url: jdbc:postgresql://doneux-website-db.cfxlcyr0taj5.eu-west-2.rds.amazonaws.com:5432/doneux_website_backend
    username: postgres
    password: LBHkjE9gLGp8pnPDvM8q

---

spring:
  profiles: test
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  datasource:
    url: jdbc:postgresql://doneux-website-db.cfxlcyr0taj5.eu-west-2.rds.amazonaws.com:5432/doneux_website_backend
    username: postgres
    password: LBHkjE9gLGp8pnPDvM8q

---

spring:
  profiles: prod
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
  datasource:
    url: jdbc:postgresql://doneux-website-db.cfxlcyr0taj5.eu-west-2.rds.amazonaws.com:5432/doneux_website_backend
    username: postgres
    password: LBHkjE9gLGp8pnPDvM8q